service: hey-office-craft-beer

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "SNS:Publish"
       Resource:
         - "*"

functions:
  craftBeerBot:
    handler: lib/handler.craftBeerBot
    environment:
      CRAFTBEER_USERNAME: ${env:CRAFTBEER_USERNAME}
      CRAFTBEER_PASSWORD: ${env:CRAFTBEER_PASSWORD}
      CRAFTBEER_ADDRESS_ID: ${env:CRAFTBEER_ADDRESS_ID}
      CRAFTBEER_CC_NAME: ${env:CRAFTBEER_CC_NAME}
      CRAFTBEER_CC_TYPE: ${env:CRAFTBEER_CC_TYPE}
      CRAFTBEER_CC_NUMBER: ${env:CRAFTBEER_CC_NUMBER}
      CRAFTBEER_CC_EXPIRY_MONTH: ${env:CRAFTBEER_CC_EXPIRY_MONTH}
      CRAFTBEER_CC_EXPIRY_YEAR: ${env:CRAFTBEER_CC_EXPIRY_YEAR}
      CRAFTBEER_CC_CCV: ${env:CRAFTBEER_CC_CCV}
      MY_PUSH_ARN: ${env:MY_PUSH_ARN}
